In [1]:
import numpy as np

import matplotlib.pyplot as plt

### 0 to 360 Case

In [2]:
a = np.arange(10,0,-1)

In [3]:
b = np.arange(360,350,-1)

In [4]:
ab = np.concatenate((a, b), axis=0)

In [5]:
ab

array([ 10,   9,   8,   7,   6,   5,   4,   3,   2,   1, 360, 359, 358,
       357, 356, 355, 354, 353, 352, 351])

In [6]:
(ab + 180) % 360 - 180

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0, -1, -2, -3, -4, -5, -6,
       -7, -8, -9])

### 360 to 0 Case

In [7]:
a = np.arange(350,360,1)

In [8]:
b = np.arange(0,10,1)

In [9]:
ab = np.concatenate((a, b), axis=0)

In [10]:
ab

array([350, 351, 352, 353, 354, 355, 356, 357, 358, 359,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9])

In [11]:
(ab + 180) % 360 - 180

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9])

### No Jump Case

In [12]:
a = np.arange(60,180,10)

In [13]:
b = np.arange(180,350,10)

In [14]:
ab = np.concatenate((a, b), axis=0)

In [15]:
ab

array([ 60,  70,  80,  90, 100, 110, 120, 130, 140, 150, 160, 170, 180,
       190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 290, 300, 310,
       320, 330, 340])

In [16]:
(ab + 180) % 360 - 360

array([-300, -290, -280, -270, -260, -250, -240, -230, -220, -210, -200,
       -190, -180, -170, -160, -150, -140, -130, -120, -110, -100,  -90,
        -80,  -70,  -60,  -50,  -40,  -30,  -20])

In [17]:
340 % 360

340